### ISSUE TITLE
Could not find a version that satisfies the requirement protobuf

### ISSUE THREAD

**Issue by ywh939** [PJLab-ADG/LoGoNet#14]
Thanks for sharing the code!

I have a problem when I try to install dependencies following your instructions, and I find protobuf>=3.20.2 requires-python: >=3.7.

<img width="935" alt="微信截图_20230511153254" src="https://github.com/PJLab-ADG/LoGoNet/assets/27114849/4318897a-986e-4901-8ab5-949beefdaadc">
<img width="526" alt="微信截图_20230511153325" src="https://github.com/PJLab-ADG/LoGoNet/assets/27114849/9a30fb7a-d82e-4685-81b0-8c420423baa8">

So I do the same work on python3.7, but meet a problem: "ModuleNotFoundError: No module named 'petrel_client'" when i run train.py.

I comment some codes, then have another problem: "No module named 'mmcv'".

I build mmcv from source, then meet problem: "AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.2.4, <=1.4.0." I install 1.4.0 by using "mim install "mmcv<=1.4.0"", but have another problem: "ModuleNotFoundError: No module named 'mmcv._ext'"

I have no idea. 

Your paper is easy to read and understand, but code env is difficult to construct.

**Comment by sankin97** [comment]
We are using mmcv-full version 1.4.0. To install it, simply run the command `pip install mmcv-full==1.4.0`.  For additional information about mmcv-full, please visit the [mmcv](https://github.com/open-mmlab/mmcv/). Btw, the closed issues also include environment configuration problems that could be relevant to your situation, which may be helpful for you.

**Comment by ywh939** [comment]
Thanks!

I fix it, but still have the problem, protobuf,  when env is python3.6 ! Did you have it on python3.6?

Now I have another one on python3.7 : 

AttributeError: 'str' object has no attribute 'exists'
<img width="747" alt="微信截图_20230511222912" src="https://github.com/PJLab-ADG/LoGoNet/assets/27114849/e358abd3-c628-4556-ab2b-5f4427033bb4">

Perhaps it's caused by python3.7?

**Comment by sankin97** [comment]
Our dataset was not stored on the local file system, sorry for this mistake. We have corrected and uploaded it, please pull it again. If you have other questions, please feel free to contact us.

**Comment by ywh939** [comment]
Wow, wonderful! 

I pull the new project just now, still run in python3.7, and now have a problem:

<img width="925" alt="微信截图_20230512173424" src="https://github.com/PJLab-ADG/LoGoNet/assets/27114849/8f43b5de-b558-4be8-a773-48949ce66b92">

I also test in python3.8. But it do not work.

This question confuses me. I have reproduced the paper VirConv which kitti code is similar with yours, they also use '/' to join path instead of os.path.join().

**Comment by sankin97** [comment]
Please try to change [line24](https://github.com/PJLab-ADG/LoGoNet/blob/3ff9872dc94b8a44b9a6b92b83fe40ba8f403281/detection/al3d_det/datasets/dataset_kitti.py#LL24C89-L24C91) into `self.root_path = root_path if root_path is not None else Path(self.dataset_cfg.DATA_PATH)`?

**Comment by ywh939** [comment]
I correct it, another one arise, i search on google, find i need to convert **path** to **str** object.

<img width="789" alt="微信截图_20230512183021" src="https://github.com/PJLab-ADG/LoGoNet/assets/27114849/eb2dc0bc-91e2-4dbb-8983-5c1113e9b998">

Probably because of you did not test code on non-Ceph, “use_shared_memory" is also Ceph config?

**Comment by sankin97** [comment]
We have uploaded a new code for Kitti and made sure to avoid using ‘s3’. Could you please pull it again? Also, just to clarify, the issue regarding ‘use_shared_memory’ is not related to Ceph. It seems like it might be caused by an error in the file path. You can find the same reference to ‘use_shared_memory’ in this [OpenPCDet](https://github.com/open-mmlab/OpenPCDet/blob/ad9c25c03cf9e866bbee8c48fa4e2860cce68a9c/pcdet/datasets/augmentor/database_sampler.py#L29).

**Comment by ywh939** [comment]
I pull the new, the error is:

<img width="777" alt="微信截图_20230512205027" src="https://github.com/PJLab-ADG/LoGoNet/assets/27114849/d9d14ca5-223e-4a7d-9993-b717a5583423">

I add the code "self.ceph=False" temporarily, it work, now the model is training.

In addition to this, i think you can comment the code  "from petrel_client.client import Client" in following two file:
/root/LoGoNet/detection/al3d_det/datasets/waymo/waymo_dataset.py
/root/LoGoNet/detection/al3d_det/datasets/nuscenes/nuscenes_dataset.py

And the command to creat kitti info should be:
`python -m al3d_det.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/det_dataset_cfgs/kitti_dataset_mm.yaml`


And i also recommend you modify Install Instuction, python3.7 not python3.6.

My env is based on Docker:

images: nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
apt-dep: install mmdetection3D apt-dependencies followed [Dockerfile](https://github.com/open-mmlab/mmdetection3d/blob/main/docker/Dockerfile)
py: python3.7
pip-dep: pip install mmcv-full==1.4.0

Othes follow LoGoNet [INSTALL](https://github.com/PJLab-ADG/LoGoNet/blob/main/docs/INSTALL.md)


I am a newer in AI, thank you very much for your help!

You are very nice! Wish you will have more papers accepted by CVPR!

**Comment by ywh939** [comment]
I pull the new, the error is:
<img width="777" alt="微信截图_20230512205027" src="https://github.com/PJLab-ADG/LoGoNet/assets/27114849/b157d06e-d078-4ace-bee6-ae88210c859a">


I add the code "self.ceph=False" before line 22, and also correct line 23 to " if 's3' not in str(prefix):" in the file _LoGoNet/detection/al3d_det/datasets/kitti/kitti_object_eval_python/kitti_common.py_ temporarily.

After, the module **can be trained**.

In addition to this, i think you can comment the code "from petrel_client.client import Client" in following two file:
_/root/LoGoNet/detection/al3d_det/datasets/waymo/waymo_dataset.py_
_/root/LoGoNet/detection/al3d_det/datasets/nuscenes/nuscenes_dataset.py_

And the command to creat kitti info should be:
`python -m al3d_det.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/det_dataset_cfgs/kitti_dataset_mm.yaml`

And i also recommend you modify Install Instuction, python3.7 not python3.6.

**My env** is based on Docker:
images: nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
apt-dep: install mmdetection3D apt-dependencies followed [Dockerfile](https://github.com/open-mmlab/mmdetection3d/blob/main/docker/Dockerfile)
py: python3.7
pip-dep: pip install mmcv-full==1.4.0

Othes follow LoGoNet [INSTALL](https://github.com/PJLab-ADG/LoGoNet/blob/main/docs/INSTALL.md)

I am a newer in AI, thank you very much for your help!
You are very nice and polite! This is the first time I saw such a quick reply! Wish you will have more papers accepted by CVPR!
